<?php
	
//logo de la institucion lado derecho
$logo="./images/logob.gif";

//logo de lado izquierdo
$escudo="./images/escudob.gif";

// nombre de la institucion
$membrete1 = "Vicepresidencia de la República";
$membrete2 = "Agencia para el Desarrollo de la Sociedad de la Informacion en Bolivia - ADSIB";

//pie de pagina de la institucion
$piepagina1="www.adsib.gob.bo  E-mail: contacto@adsib.gob.bo";
$piepagina2="Telfs./Fax 2 200720/30/40        Calle Ayacucho y Mercado # 308 Edif. de la Vocepresidencia de la República Piso 3";

?>